
server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_course
    username: root
    password: 271757
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall

      #      开启监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.why.boot.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
#          config:
#            update-allow: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


